base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('user/', include('user.urls', namespace='user')),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('glass/', views.glass, name='glass'),
    path('contact/', views.contact, name='contact'),
    path('store/', views.store, name='store'),
    path('category/<int:category_id>/', views.store, name='category'),
    path('basket/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profilecart/', views.profile_cart, name='profilecart'),
    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

shop/models.py
from django.db import models
from django.utils import timezone

from user.models import User


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    price = models.IntegerField(default=1)
    created_at = models.DateTimeField(default=timezone.now)
    quantity = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='products_images')

    def __str__(self) -> str:
        return f"Name: {self.name}, Category: {self.category}"

    class Meta:
        verbose_name_plural = "Products"
        verbose_name = 'Product'


class BasketQuerySet(models.QuerySet):
    def total_summ(self) -> int:
        return sum(basket.sum() for basket in self)

    def total_quantity(self) -> int:
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self) -> str:
        return f'Cart for: {self.user.username} | Product: {self.product.name}'

    def sum(self) -> int:
        return self.product.price * self.quantity

shop/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import HttpResponseRedirect, render

from .models import Basket, Category, Product


def index(request: HttpRequest) -> HttpResponse:
    return render(request, 'shop/index.html')


def about(request: HttpRequest) -> HttpResponse:
    return render(request, 'shop/about.html')


def glass(request: HttpRequest) -> HttpResponse:
    return render(request, 'shop/glass.html')


def contact(request: HttpRequest) -> HttpResponse:
    return render(request, 'shop/contact.html')


def store(request: HttpRequest, category_id=None) -> HttpResponse:
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    context = {
        'products': products,
        'categories': Category.objects.all(),
    }

    return render(request, 'shop/store.html', context)


@login_required
def basket_add(request: HttpRequest, product_id: int) -> HttpResponse:
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request: HttpRequest, basket_id: int) -> HttpResponse:
    basket = Basket.objects.get(id=basket_id)
    basket.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                <span>About</span> our shop
              </h2>
            </div>
            <p>
              It is a long established fact that a reader will be distracted by the readable content of a page when
              looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of
              letters,
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="img-box">
            <img src="{% static 'images/about-img.png'%}" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  {% endblock %}

templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Sglass</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="css/responsive.css" rel="stylesheet" />

  <style>
    ::-webkit-scrollbar {
        width: 5px;
    }

    ::-webkit-scrollbar-track {
        background-color: #111215;
    }

    ::-webkit-scrollbar-thumb {
        background-color: #555;
        border-radius: 50px;
    }

    ::-webkit-scrollbar-thumb:hover {
        background-color: #A1A1AA;

    }
</style>
</head>

<body>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
          <a class="navbar-brand mr-5" href="{% url "shop:index" %}">
            <span>
              Sglass
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex mr-auto flex-column flex-lg-row align-items-center">
              <ul class="navbar-nav  ">
                <li class="nav-item">
                  <a class="nav-link" href="{% url "shop:index" %}">Home </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url "shop:about" %}"> About </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url "shop:store" %}"> Shop </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url "shop:glass" %}"> Glasses </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url "shop:contact" %}">Contact us</a>
                </li>
              </ul>
            </div>
            <div class="quote_btn-container ">
              {% if user.is_authenticated %}
              <a href="{% url "user:profilecart" %}">
                PROFILE & CART
              </a>
              <a class="ml-5" href="{% url "user:logout" %}">
                Log out
              </a>
            {% else %}
                <a class="ml-5" href="{% url "user:login" %}">
                  Log in
                </a>
            {% endif %}
              </div>

          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->

    {% block content %}{% endblock %}

     <!-- info section -->

  <section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <h6>
            Subscribe Now
          </h6>
          <form action="">
            <input type="text" placeholder="Enter your email">
            <div class="d-flex justify-content-end">
              <button>
                submit
              </button>
            </div>
          </form>
        </div>
        <div class="col-md-3 offset-md-1">
          <h6>
            Links
          </h6>
          <ul>
            <li>
              <a href="">
                Lorem ipsum dolor sit
              </a>
            </li>
            <li>
              <a href="">
                amet, consectetur adipis
              </a>
            </li>
            <li>
              <a href="">
                cing elit, sed do
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <h6>
            Contact us
          </h6>
          <ul>
            <li>
              <a href="">
                Lorem ipsum dolor sit
              </a>
            </li>
            <li>
              <a href="">
                amet, consectetur adipis
              </a>
            </li>
            <li>
              <a href="">
                cing elit, sed do
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->


  <!-- footer section -->
  <section class="container-fluid footer_section">
    <p>
      Copyright &copy; <span id="displayYear"></span> All Rights Reserved By
      <a href="https://html.design/">Free Html Templates</a>
    </p>
  </section>
  <!-- footer section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js'%}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js'%}"></script>

</body>

</html>

templates/shop/basket.html
{% load static %}

{% if baskets %}

<div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Cart <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
            </h4>
            {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} $</div>
                            <div class="col-lg-4">
                                <a href="{% url 'shop:basket_remove' basket.id %}">
                                    DELETE

                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            {% endfor %}
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Total summ</p>
                    <h4 class="float-right">{{ baskets.total_summ }} $</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Apply
            </a>
        </div>
    </div>
</div>

{% else %}
<h4 class="mt-3 mb-3 text-center">
    The cart is empty
{% endif %}

templates/shop/contact.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<section class="contact_section layout_padding">
  <div class="container">
    <h2>
      Request A call back
    </h2>
    <div class="">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <form action="">
            <div class="contact_form-container">
              <div>
                <div>
                  <input type="text" placeholder="Name">
                </div>
                <div>
                  <input type="text" placeholder="Phone Number">
                </div>
                <div>
                  <input type="email" placeholder="Email">
                </div>
                <div class="">
                  <input type="text" placeholder="Message" class="message_input">
                </div>
                <div class="mt-5 d-flex justify-content-center ">
                  <button type="submit">
                    Send
                  </button>
                </div>
              </div>

            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock  %}

templates/shop/glass.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}

  <!-- quality section -->

  <section class="quality_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          <span> Best</span> Quality
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <ul class="nav nav-tabs detail-box" id="myTab" role="tablist">
            <li class="">
              <a class=" active" id="QTab1Link" data-toggle="tab" href="#qTab1" role="tab" aria-controls="qTab1" aria-selected="true">
                <h6 id="QTab1Link" data-toggle="tab" href="#qTab1" role="tab" aria-controls="qTab1" aria-selected="true">
                  <span>01</span>
                  It is a long established fact that a reader will be distracted
                </h6>
              </a>
            </li>
            <li class="">
              <a class="" id="QTab2Link" data-toggle="tab" href="#qTab2" role="tab" aria-controls="qTab2" aria-selected="false">
                <h6 id="QTab2Link" data-toggle="tab" href="#qTab2" role="tab" aria-controls="qTab2" aria-selected="false">
                  <span>02</span>
                  by the readable content of a page when looking at its
                </h6>
              </a>
            </li>
            <li class="">
              <a class="" id="QTab3Link" data-toggle="tab" href="#qTab3" role="tab" aria-controls="qTab3" aria-selected="false">
                <h6 id="QTab3Link" data-toggle="tab" href="#qTab3" role="tab" aria-controls="qTab3" aria-selected="false">
                  <span>03</span>
                  layout. The point of using Lorem Ipsum is that it has a
                </h6>
              </a>
            </li>
            <li class="">
              <a class="" id="QTab4Link" data-toggle="tab" href="#qTab4" role="tab" aria-controls="qTab4" aria-selected="false">
                <h6 id="QTab4Link" data-toggle="tab" href="#qTab4" role="tab" aria-controls="qTab4" aria-selected="false">
                  <span>04</span>
                  more-or-less normal distribution of letters,
                </h6>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-6 tab-content">
          <div class="img-container tab-pane  fade show active" id="qTab1" role="tabpanel" aria-labelledby="QTab1Link">
            <div class="img-box ">
              <img src="{% static 'images/quality-img.jpg'%}" alt="">
            </div>
          </div>
          <div class="img-container tab-pane fade" id="qTab2" role="tabpanel" aria-labelledby="QTab2Link">
            <div class="img-box  ">
              <img src="{% static 'images/buy-img.png' %}" alt="">
            </div>
          </div>
          <div class="img-container tab-pane fade" id="qTab3" role="tabpanel" aria-labelledby="QTab3Link">
            <div class="img-box  ">
              <img src="{%static 'images/quality-img.jpg'%}" alt="">
            </div>
          </div>
          <div class="img-container tab-pane fade" id="qTab4" role="tabpanel" aria-labelledby="QTab4Link">
            <div class="img-box  ">
              <img src="{%static 'images/buy-img.png'%}" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- end quality section -->

  <!-- offer section -->

  <section class="offer_section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-7 px-0">
          <div class="img-box">
            <img src="images/offer-img.jpg" alt="">
            <div class="price">
              <h4>
                $60
              </h4>
            </div>
          </div>
        </div>
        <div class="col-md-4 offset-md-1">
          <div class="detail-box">
            <h2>
              Book <br>
              our <br>
              special <br>
              offer
            </h2>
            <a href="">
              See More offer
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- end offer section -->

  <!-- buy section -->

  <section class="buy_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          <span class="s-1">
            Buy
          </span>
          your stylish
          <span class="s-2">
            glasses
          </span>
        </h2>
      </div>
      <div class="box">
        <div class="img-box">
          <img src="images/buy-img.png" alt="">
        </div>
        <div class="detail-box">
          <p>
            It is a long established fact that a reader will be distracted by the readable content of a page when
            looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of
            letters, <br>
            It is a long established fact that a reader will be distracted by the readable content of a page when
            looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of
            letters,
          </p>
          <a href="">
            Book Now
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- end buy section -->

  {% endblock  %}

templates/shop/store.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}

  <section class="glass_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          <span> Our </span> Glasses
        </h2>
      </div>
      <div class="d-flex justify-content-between">
      {% for category in categories %}
        <a class="btn btn-info w-25 p-10 mb-4" href="{% url 'shop:category' category.id %}">{{ category.name }}</a>
        {% endfor %}
        <a class="btn btn-info w-25 p-10 mb-4" href="{% url 'shop:store' %}">All glass</a>
      </div>
      <div class="glass_container">
        {% for product in products %}
        <div class="box">
          <div class="img-box">
            <img src="{{ product.image.url }}" alt="image">
          </div>
          <div class="price">
            <h6>
              <p>{{ product.price }} $</p>
            </h6>
            <a href="{% url 'shop:basket_add' product.id %}">
              Buy Now
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="btn-box">
      </div>
    </div>
  </section>
  {% comment %} {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous  %} disabled {% endif %}">
                        <a class="page-link"
                        href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                        tabindex="-1" aria-disabled="true">
                        Предыдущая
                    </a>
                    </li>
                    {% for page in paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'products:paginator' page %}">
                                {{ page }}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                        href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                        Слеудующая
                    </a>
                    </li>
                </ul>
            </nav> {% endcomment %}
            {% comment %} {% endif %} {% endcomment %}

{% endblock %}