base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('user/', include('user.urls', namespace='user')),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('glass/', views.glass, name='glass'),
    path('contact/', views.contact, name='contact'),
    path('store/', views.store, name='store'),
    path('category/<int:category_id>/', views.store, name='category'),
    path('basket/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profilecart/', views.profile_cart, name='profilecart'),
    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

user/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('user    :email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = f'Для подтверждения учетной записи {self.user.email} перейдите по ссылке {verification_link}'

        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm

from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'username',
        'placeholder': 'Name'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password',
        'placeholder': 'Password'

    }))

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'username  ',
        'placeholder': 'Username'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'email',
        'placeholder': 'Email'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password1',
        'placeholder': 'Password'

    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password2',
        'placeholder': 'Repeat password'

    }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True,
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True,
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input',
    }), required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'image']

user/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse
from django.views.generic import TemplateView

from shop.models import Basket
from user.models import User

from .forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from .models import EmailVerification


def registration(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulations! You have successfully registered!')

            return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserRegistrationForm

    context = {'form': form}

    return render(request, 'user/registration.html', context)


def login(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)

        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user:
                auth.login(request, user)

                return HttpResponseRedirect(reverse('shop:index'))
    else:
        form = UserLoginForm()

    context = {'form': form}

    return render(request, 'user/login.html', context)


@login_required
def profile_cart(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('user:profilecart'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)

    context = {'form': form, 'baskets': Basket.objects.filter(user=request.user)}

    return render(request, 'user/profile_cart.html', context)


def logout(request: HttpRequest) -> HttpResponse:
    auth.logout(request)

    return HttpResponseRedirect(reverse('shop:index'))


class EmailVerificationView(TemplateView):
    template_name = 'user/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)

        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))

templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sglass</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/reglog.css' %}">

    <style>
        ::-webkit-scrollbar {
            width: 5px;
        }

        ::-webkit-scrollbar-track {
            background-color: #111215;
        }

        ::-webkit-scrollbar-thumb {
            background-color: #555;
            border-radius: 50px;
        }

        ::-webkit-scrollbar-thumb:hover {
            background-color: #A1A1AA;

        }
    </style>
</head>
<body>

    <div class="main">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/user/email_verification.html
{% extends "user/base.html" %}
{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Congratulations!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Your account has been successfully verified!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'user:login' %}">Continue</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/user/login.html
{% extends 'user/base.html' %}
{% load static %}

{% load socialaccount %}


{% block content %}

    <div class="row text-center">
        <div class="col-lg-5">
            {% if messages or form.non_field_errors %}
            <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                            {{ message }}
                    {% endfor %}
            {% else %}
                {{ form.non_field_errors  }}
            {% endif %}
            </div>
            {% endif %}


<!-- Sing in  Form -->
<section class="sign-in">
    <div class="container">
        <div class="signin-content">
            <div class="signin-image">
                <figure><img src="{% static 'images/signin-image.jpg' %}"></figure>
                <a href="{% url "user:registration" %}" class="signup-image-link">Create an account</a>
            </div>

            <div class="signin-form">
                <h2 class="form-title">Sign in</h2>
                <form action="{% url 'user:login' %}" method="POST" class="register-form" id="login-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="form.username.id_for_lable"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label for="form.password.id_for_lable"><i class="zmdi zmdi-lock"></i></label>
                        {{ form.password }}
                    </div>
                    {% comment %} <div class="form-group">
                        <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                        <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                    </div> {% endcomment %}
                    <div class="form-group form-button">
                        <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                    </div>
                </form>
                <div class="social-login">
                    <span class="social-label">Or login with</span>
                    <ul class="socials">
                        <a href="{% provider_login_url 'github' %}">GitHub<i class="fab fa-github fa-2x" style="color: #303030;"></i></a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/user/profile_cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Sglass - Profile & Cart</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css'%}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.17.0/font/bootstrap-icons.css" rel="stylesheet">




  <style>
    ::-webkit-scrollbar {
        width: 5px;
    }

    ::-webkit-scrollbar-track {
        background-color: #111215;
    }

    ::-webkit-scrollbar-thumb {
        background-color: #555;
        border-radius: 50px;
    }

    ::-webkit-scrollbar-thumb:hover {
        background-color: #A1A1AA;

    }
</style>

</head>
<body class="bg-light">
     <!-- header section strats -->
     <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
            <a class="navbar-brand mr-5" href="{% url "shop:index" %}">
              <span>
                Sglass
              </span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="d-flex mr-auto flex-column flex-lg-row align-items-center">
                <ul class="navbar-nav  ">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:index" %}">Home </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:about" %}"> About </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:store" %}"> Shop </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:glass" %}"> Glasses </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:contact" %}">Contact us</a>
                  </li>
                </ul>
              </div>
              <div class="quote_btn-container ">
                {% if user.is_authenticated %}
              <a href="{% url "user:profilecart" %}">
                PROFILE & CART
              </a>
              <a class="ml-5" href="{% url "user:logout" %}">
                Log out
              </a>
            {% else %}
                <a class="ml-5" href="{% url "user:login" %}">
                  Log in
                </a>
            {% endif %}
              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- end header section -->

<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Profile</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'images/default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'user:profilecart' %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                {% comment %} <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="inputFirstName">First name</label>
                            <input class="form-control py-4" id="inputFirstName" type="text" value=""/>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="inputLastName">Last name</label>
                            <input class="form-control py-4" id="inputLastName" type="text" value=""/>
                        </div>
                    </div>
                </div> {% endcomment %}
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                          <label class="custom-file-label" for="{{ form.image.id_for_lable }}">Image</label>
                          {{ form.image }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                      <label class="small mb-1" for="{{ form.username.id_for_lable }}">Username</label>
                      {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_lable }}">Email</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Save">
                    </div>
                </div>
            </form>
        </div>
        {% include 'shop/basket.html' %}

<!-- Bootstrap core JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js'%}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js'%}"></script>
</body>
</html>

templates/user/registration.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}

<div class="col-lg-7">
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert"
    style="margin-top: 50px;">
   {{ form.errors }}
</div>
    {% endif %}

<!-- Sign up form -->
<section class="signup">
    <div class="container">
        <div class="signup-content">
            <div class="signup-form">
                <h2 class="form-title">Sign up</h2>
                <form action="{% url 'user:registration' %}" method="POST" class="register-form" id="register-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="form.username.id_for_lable"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label for="form.email.id_for_lable"><i class="zmdi zmdi-email"></i></label>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="form.password1.id_for_lable"><i class="zmdi zmdi-lock"></i></label>
                        {{ form.password1 }}
                    </div>
                    <div class="form-group">
                        <label for="form.password2.id_for_lable"><i class="zmdi zmdi-lock-outline"></i></label>
                        {{ form.password2 }}
                    </div>
                        {% comment %} <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                        </div> {% endcomment %}
                    <div class="form-group form-button">
                        <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                    </div>
                </form>
            </div>
            <div class="signup-image">
                <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                <a href="{% url "user:login" %}" class="signup-image-link">I am already member</a>
            </div>
        </div>
    </div>
</section>

{% endblock content %}